language: cpp

env:
  - CLONE_FLAGS=0
  - CLONE_FLAGS="CLONE_NEWIPC"
  - CLONE_FLAGS="CLONE_NEWNET"
  - CLONE_FLAGS="CLONE_NEWPID"
  - CLONE_FLAGS="CLONE_NEWNET|CLONE_NEWPID"
  - CLONE_FLAGS="CLONE_NEWIPC|CLONE_NEWNET"
  - CLONE_FLAGS="CLONE_NEWIPC|CLONE_NEWPID"
  - CLONE_FLAGS="CLONE_NEWIPC|CLONE_NEWNET|CLONE_NEWPID"

before_script:
  - ./configure
  - make CEXTRA="-DCLONE_FLAGS='$CLONE_FLAGS'"
  - sudo chown root obj/isolate/isolate
  - sudo chmod 4750 obj/isolate/isolate

script:
  - echo "Linux Kernel:" "`uname -r`"
  - ./obj/isolate/isolate --init
  - ./obj/isolate/isolate --run -- /bin/ls /
  - ./obj/isolate/isolate --cleanup

